// <auto-generated />
#nullable enable

namespace FbSample.Views.Pages;

partial class MonitorPage
{
    private System.ComponentModel.IContainer? components = null;

    /// <inheritdoc />
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        SuspendLayout();
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        BackColor = Color.FromArgb(243, 243, 243);
        Font = new Font("Microsoft YaHei UI", 10F);
        Name = "MonitorPage";
        Size = new Size(966, 567);
        ResumeLayout(false);
    }
}
