// <auto-generated />
#nullable enable

namespace FbSample.Views;

partial class MainForm
{
    private System.ComponentModel.IContainer? components = null;
    private AntdUI.PageHeader _titleBar;
    private AntdUI.Input _searchInput;
    private AntdUI.Dropdown _languageDropdown;
    private AntdUI.Button _themeButton;
    private AntdUI.Button _aboutButton;
    private AntdUI.Button _collapseButton;
    private AntdUI.Button _backButton;
    private AntdUI.Avatar _navigationLogo;
    private AntdUI.Label _brandLabel;
    private AntdUI.TooltipComponent _navigationTooltips;
    private AntdUI.Panel _navigationHeaderPanel;
    private AntdUI.Panel _navigationToolsPanel;
    private AntdUI.Panel _navigationDivider;
    private AntdUI.Panel _workspacePanel;
    private AntdUI.Panel _contentPanel;
    private Pages.DashboardPage _dashboardPage;
    private Controls.NavigationMenu _navigationMenu;
    private AntdUI.Panel _navigationPanel;

    /// <inheritdoc />
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _navigationMenu.CloseFlyout();
            Microsoft.Win32.SystemEvents.UserPreferenceChanged -= SystemPreferenceChanged;
            _navigationTooltips.Dispose();
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    [System.Diagnostics.CodeAnalysis.MemberNotNull(nameof(_titleBar), nameof(_searchInput), nameof(_languageDropdown), nameof(_themeButton), nameof(_aboutButton), nameof(_collapseButton), nameof(_backButton), nameof(_navigationLogo), nameof(_brandLabel), nameof(_navigationTooltips), nameof(_navigationHeaderPanel), nameof(_navigationToolsPanel), nameof(_navigationDivider), nameof(_workspacePanel), nameof(_contentPanel), nameof(_dashboardPage), nameof(_navigationMenu), nameof(_navigationPanel))]
    private void InitializeComponent()
    {
        AntdUI.MenuItem dashboardItem = new AntdUI.MenuItem();
        AntdUI.MenuItem devicesItem = new AntdUI.MenuItem();
        AntdUI.MenuItem monitorItem = new AntdUI.MenuItem();
        AntdUI.MenuItem logsItem = new AntdUI.MenuItem();
        AntdUI.MenuItem logsPage1Item = new AntdUI.MenuItem();
        AntdUI.MenuItem logsPage2Item = new AntdUI.MenuItem();
        AntdUI.MenuItem debugItem = new AntdUI.MenuItem();
        AntdUI.MenuItem debugPage1Item = new AntdUI.MenuItem();
        AntdUI.MenuItem settingsItem = new AntdUI.MenuItem();
        _titleBar = new AntdUI.PageHeader();
        _searchInput = new AntdUI.Input();
        _languageDropdown = new AntdUI.Dropdown();
        _themeButton = new AntdUI.Button();
        _aboutButton = new AntdUI.Button();
        _collapseButton = new AntdUI.Button();
        _backButton = new AntdUI.Button();
        _navigationLogo = new AntdUI.Avatar();
        _brandLabel = new AntdUI.Label();
        _navigationTooltips = new AntdUI.TooltipComponent();
        _navigationTooltips.ArrowAlign = AntdUI.TAlign.Right;
        _navigationHeaderPanel = new AntdUI.Panel();
        _navigationToolsPanel = new AntdUI.Panel();
        _navigationDivider = new AntdUI.Panel();
        _workspacePanel = new AntdUI.Panel();
        _contentPanel = new AntdUI.Panel();
        _dashboardPage = new Pages.DashboardPage();
        _navigationMenu = new Controls.NavigationMenu();
        _navigationPanel = new AntdUI.Panel();
        _titleBar.SuspendLayout();
        _contentPanel.SuspendLayout();
        _navigationPanel.SuspendLayout();
        _navigationHeaderPanel.SuspendLayout();
        _navigationToolsPanel.SuspendLayout();
        _workspacePanel.SuspendLayout();
        SuspendLayout();
        dashboardItem.Name = "Dashboard";
        dashboardItem.Text = "Dashboard";
        dashboardItem.IconSvg = "HomeOutlined";
        devicesItem.Name = "Devices";
        devicesItem.Text = "Devices";
        devicesItem.IconSvg = "ClusterOutlined";
        monitorItem.Name = "Monitor";
        monitorItem.Text = "Monitor";
        monitorItem.IconSvg = "DesktopOutlined";
        logsItem.Name = "Logs";
        logsItem.Text = "Logs";
        logsItem.IconSvg = "FileTextOutlined";
        logsPage1Item.Name = "LogsPage1";
        logsPage1Item.Text = "LogsPage1";
        logsPage1Item.IconSvg = "FileTextOutlined";
        logsPage2Item.Name = "LogsPage2";
        logsPage2Item.Text = "LogsPage2";
        logsPage2Item.IconSvg = "FileTextOutlined";
        debugItem.Name = "Debug";
        debugItem.Text = "Debug";
        debugItem.IconSvg = "BugOutlined";
        debugPage1Item.Name = "DebugPage1";
        debugPage1Item.Text = "DebugPage1";
        debugPage1Item.IconSvg = "CodeOutlined";
        settingsItem.Name = "Settings";
        settingsItem.Text = "Settings";
        settingsItem.IconSvg = "SettingOutlined";
        logsItem.Sub.Add(logsPage1Item);
        logsItem.Sub.Add(logsPage2Item);
        debugItem.Sub.Add(debugPage1Item);
        // _titleBar
        _titleBar.Name = "_titleBar";
        _titleBar.BackColor = Color.FromArgb(247, 247, 247);
        _titleBar.Controls.Add(_searchInput);
        _titleBar.Controls.Add(_languageDropdown);
        _titleBar.Controls.Add(_themeButton);
        _titleBar.Controls.Add(_aboutButton);
        _titleBar.DividerShow = true;
        _titleBar.Dock = DockStyle.Top;
        _titleBar.Location = new Point(0, 0);
        _titleBar.ShowButton = true;
        _titleBar.ShowIcon = false;
        _titleBar.Size = new Size(966, 36);
        // _searchInput
        _searchInput.Name = "_searchInput";
        _searchInput.AllowClear = true;
        _searchInput.Dock = DockStyle.Right;
        _searchInput.LocalizationPlaceholderText = "Search";
        _searchInput.Location = new Point(472, 0);
        _searchInput.PlaceholderText = "Search";
        _searchInput.PrefixSvg = "SearchOutlined";
        _searchInput.Size = new Size(200, 36);
        _searchInput.TabIndex = 0;
        _searchInput.TextChanged += SearchChanged;
        // _languageDropdown
        _languageDropdown.Name = "_languageDropdown";
        _languageDropdown.Dock = DockStyle.Right;
        _languageDropdown.Ghost = true;
        _languageDropdown.IconSvg = "TranslationOutlined";
        _languageDropdown.Items.AddRange(new object[] { "English", "简体中文", "繁體中文" });
        _languageDropdown.Location = new Point(672, 0);
        _languageDropdown.Placement = AntdUI.TAlignFrom.BR;
        _languageDropdown.Size = new Size(50, 36);
        _languageDropdown.TabIndex = 1;
        _languageDropdown.Trigger = AntdUI.Trigger.Hover;
        _languageDropdown.WaveSize = 0;
        _languageDropdown.SelectedValueChanged += LanguageChanged;
        // _themeButton
        _themeButton.Name = "_themeButton";
        _themeButton.Dock = DockStyle.Right;
        _themeButton.Ghost = true;
        _themeButton.IconSvg = "SunOutlined";
        _themeButton.Location = new Point(722, 0);
        _themeButton.Radius = 0;
        _themeButton.Size = new Size(50, 36);
        _themeButton.TabIndex = 2;
        _themeButton.ToggleIconSvg = "MoonOutlined";
        _themeButton.WaveSize = 0;
        _themeButton.Click += ThemeClicked;
        // _aboutButton
        _aboutButton.Name = "_aboutButton";
        _aboutButton.Dock = DockStyle.Right;
        _aboutButton.Ghost = true;
        _aboutButton.IconSvg = "InfoCircleOutlined";
        _aboutButton.Location = new Point(772, 0);
        _aboutButton.Radius = 0;
        _aboutButton.Size = new Size(50, 36);
        _aboutButton.TabIndex = 3;
        _aboutButton.WaveSize = 0;
        _aboutButton.Click += AboutClicked;
        // _collapseButton
        _collapseButton.Name = "_collapseButton";
        _collapseButton.Ghost = true;
        _collapseButton.IconRatio = 0.9150327F;
        _collapseButton.IconSvg = "MenuOutlined";
        _collapseButton.Location = new Point(4, 0);
        _collapseButton.Radius = 5;
        _collapseButton.Size = new Size(49, 41);
        _collapseButton.TabIndex = 1;
        _collapseButton.WaveSize = 0;
        _collapseButton.Click += CollapseClicked;
        // _backButton
        _backButton.Name = "_backButton";
        _backButton.AccessibleName = "Back";
        _backButton.Enabled = false;
        _backButton.Ghost = true;
        _backButton.IconRatio = 0.9150327F;
        _backButton.ToggleIconSvg = "ArrowLeftOutlined";
        _backButton.Location = new Point(4, 4);
        _backButton.Radius = 5;
        _backButton.Size = new Size(49, 41);
        _backButton.TabIndex = 0;
        _backButton.Visible = false;
        _backButton.WaveSize = 0;
        _backButton.Click += BackClicked;
        // _navigationLogo
        _navigationLogo.Name = "_navigationLogo";
        _navigationLogo.AccessibleName = "FbSample";
        _navigationLogo.AccessibleRole = AccessibleRole.Graphic;
        _navigationLogo.Image = Properties.Resources.NavigationLogo;
        _navigationLogo.ImageFit = AntdUI.TFit.Contain;
        _navigationLogo.Location = new Point(20, 16);
        _navigationLogo.Radius = 0;
        _navigationLogo.Size = new Size(17, 17);
        _navigationLogo.TabStop = false;
        // _brandLabel
        _brandLabel.Name = "_brandLabel";
        _brandLabel.Location = new Point(64, 4);
        _brandLabel.Size = new Size(179, 41);
        _brandLabel.Text = "FbSample";
        _brandLabel.Visible = false;
        // _navigationHeaderPanel
        _navigationHeaderPanel.Name = "_navigationHeaderPanel";
        _navigationHeaderPanel.Back = Color.Transparent;
        _navigationHeaderPanel.Controls.Add(_navigationLogo);
        _navigationHeaderPanel.Controls.Add(_backButton);
        _navigationHeaderPanel.Controls.Add(_brandLabel);
        _navigationHeaderPanel.Dock = DockStyle.Top;
        _navigationHeaderPanel.Radius = 0;
        _navigationHeaderPanel.Size = new Size(57, 47);
        _navigationHeaderPanel.TabIndex = 0;
        // _navigationToolsPanel
        _navigationToolsPanel.Name = "_navigationToolsPanel";
        _navigationToolsPanel.Back = Color.Transparent;
        _navigationToolsPanel.Controls.Add(_collapseButton);
        _navigationToolsPanel.Dock = DockStyle.Top;
        _navigationToolsPanel.Location = new Point(0, 47);
        _navigationToolsPanel.Radius = 0;
        _navigationToolsPanel.Size = new Size(57, 43);
        _navigationToolsPanel.TabIndex = 1;
        // _navigationDivider
        _navigationDivider.Name = "_navigationDivider";
        _navigationDivider.Back = Color.FromArgb(225, 230, 234);
        _navigationDivider.Dock = DockStyle.Right;
        _navigationDivider.Location = new Point(57, 0);
        _navigationDivider.Radius = 0;
        _navigationDivider.Size = new Size(1, 640);
        // _workspacePanel
        _workspacePanel.Name = "_workspacePanel";
        _workspacePanel.Back = Color.FromArgb(243, 243, 243);
        _workspacePanel.BackColor = Color.FromArgb(243, 243, 243);
        _workspacePanel.Controls.Add(_contentPanel);
        _workspacePanel.Controls.Add(_titleBar);
        _workspacePanel.Dock = DockStyle.Fill;
        _workspacePanel.Location = new Point(58, 0);
        _workspacePanel.Radius = 0;
        _workspacePanel.Size = new Size(966, 640);
        _workspacePanel.TabIndex = 1;
        // _contentPanel
        _contentPanel.Name = "_contentPanel";
        _contentPanel.Back = Color.FromArgb(243, 243, 243);
        _contentPanel.BackColor = Color.FromArgb(243, 243, 243);
        _contentPanel.Controls.Add(_dashboardPage);
        _contentPanel.Dock = DockStyle.Fill;
        _contentPanel.Location = new Point(0, 36);
        _contentPanel.Radius = 0;
        _contentPanel.Size = new Size(966, 604);
        _contentPanel.TabIndex = 2;
        // _dashboardPage
        _dashboardPage.Name = "_dashboardPage";
        _dashboardPage.Dock = DockStyle.Fill;
        _dashboardPage.Location = new Point(0, 0);
        _dashboardPage.Size = new Size(966, 604);
        // _navigationMenu
        _navigationMenu.Name = "_navigationMenu";
        _navigationMenu.BackColor = Color.FromArgb(239, 244, 249);
        _navigationMenu.Collapsed = true;
        _navigationMenu.Dock = DockStyle.Fill;
        _navigationMenu.IconGap = 27;
        _navigationMenu.IconRatio = 1F;
        _navigationMenu.Indent = true;
        _navigationMenu.Items.AddRange(new AntdUI.MenuItem[] { dashboardItem, devicesItem, monitorItem, logsItem, debugItem, settingsItem });
        _navigationMenu.Location = new Point(0, 90);
        _navigationMenu.Padding = new Padding(4, 0, 4, 4);
        _navigationMenu.Size = new Size(57, 550);
        _navigationMenu.TabIndex = 2;
        _navigationMenu.Unique = true;
        _navigationMenu.ItemClick += NavigationClicked;
        // _navigationPanel
        _navigationPanel.Name = "_navigationPanel";
        _navigationPanel.Back = Color.FromArgb(239, 244, 249);
        _navigationPanel.BackColor = Color.FromArgb(239, 244, 249);
        _navigationPanel.Controls.Add(_navigationMenu);
        _navigationPanel.Controls.Add(_navigationToolsPanel);
        _navigationPanel.Controls.Add(_navigationHeaderPanel);
        _navigationPanel.Controls.Add(_navigationDivider);
        _navigationPanel.Location = new Point(0, 0);
        _navigationPanel.Radius = 0;
        _navigationPanel.Size = new Size(58, 640);
        _navigationPanel.TabIndex = 0;
        // MainForm
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        BackColor = Color.White;
        ClientSize = new Size(1024, 640);
        ControlBox = false;
        Controls.Add(_navigationPanel);
        Controls.Add(_workspacePanel);
        Font = new Font("Microsoft YaHei UI", 10F);
        Icon = Properties.Resources.AppIcon;
        MinimumSize = new Size(900, 560);
        Name = "MainForm";
        Padding = new Padding(58, 0, 0, 0);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "FbSample";
        Layout += ShellLayout;
        _titleBar.ResumeLayout(false);
        _contentPanel.ResumeLayout(false);
        _navigationPanel.ResumeLayout(false);
        _navigationHeaderPanel.ResumeLayout(false);
        _navigationToolsPanel.ResumeLayout(false);
        _workspacePanel.ResumeLayout(false);
        ResumeLayout(false);
    }
}
