// <auto-generated />
#nullable enable

namespace FbSample.Views.Controls;

partial class NavigationFlyoutControl
{
    private System.ComponentModel.IContainer? components = null;
    private AntdUI.Panel _navigationFlyoutPanel;
    private NavigationMenu _navigationFlyoutMenu;

    /// <inheritdoc />
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    [System.Diagnostics.CodeAnalysis.MemberNotNull(nameof(_navigationFlyoutPanel), nameof(_navigationFlyoutMenu))]
    private void InitializeComponent()
    {
        _navigationFlyoutPanel = new AntdUI.Panel();
        _navigationFlyoutMenu = new NavigationMenu();
        _navigationFlyoutPanel.SuspendLayout();
        SuspendLayout();
        // _navigationFlyoutPanel
        _navigationFlyoutPanel.Name = "_navigationFlyoutPanel";
        _navigationFlyoutPanel.Back = Color.FromArgb(247, 247, 247);
        _navigationFlyoutPanel.BackColor = Color.FromArgb(243, 243, 243);
        _navigationFlyoutPanel.BorderColor = Color.FromArgb(204, 204, 204);
        _navigationFlyoutPanel.BorderWidth = 1F;
        _navigationFlyoutPanel.Controls.Add(_navigationFlyoutMenu);
        _navigationFlyoutPanel.Dock = DockStyle.Fill;
        _navigationFlyoutPanel.Location = Point.Empty;
        _navigationFlyoutPanel.Padding = new Padding(4);
        _navigationFlyoutPanel.Radius = 8;
        _navigationFlyoutPanel.Shadow = 8;
        _navigationFlyoutPanel.ShadowColor = Color.Black;
        _navigationFlyoutPanel.ShadowDelay = 0;
        _navigationFlyoutPanel.ShadowOpacity = 0.12F;
        _navigationFlyoutPanel.ShadowOpacityAnimation = false;
        _navigationFlyoutPanel.Size = new Size(166, 122);
        _navigationFlyoutPanel.TabIndex = 0;
        // _navigationFlyoutMenu
        _navigationFlyoutMenu.Name = "_navigationFlyoutMenu";
        _navigationFlyoutMenu.BackColor = Color.FromArgb(247, 247, 247);
        _navigationFlyoutMenu.Dock = DockStyle.Fill;
        _navigationFlyoutMenu.Location = new Point(13, 13);
        _navigationFlyoutMenu.Padding = new Padding(4);
        _navigationFlyoutMenu.Size = new Size(140, 96);
        _navigationFlyoutMenu.TabIndex = 0;
        // NavigationFlyoutControl
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        BackColor = Color.FromArgb(243, 243, 243);
        Controls.Add(_navigationFlyoutPanel);
        Font = new Font("Microsoft YaHei UI", 10F);
        Name = "NavigationFlyoutControl";
        Size = new Size(166, 122);
        _navigationFlyoutPanel.ResumeLayout(false);
        ResumeLayout(false);
    }
}
